lang: "zh_cn"

disabled-jobs: [ ]

lobbies:
  hub:
    location: [ 0, 100, 0 ]
    range:
      from: [ 100, 100 ]
      to: [ -100, -100 ]
    entry:
      time: 3000 # ms
      from: [ 9, 103, 1 ]
      to: [ 11, 100, -1 ]

  death:
    location: [ -500, 100, -500 ]
    range:
      from: [ -600, -600 ]
      to: [ -400, -400 ]

game:
  disabled-modes: [ ]

  # Shared game-level settings owned by core.
  leave-delay-seconds: 5

ui:
  lobby:
    job-select-mode: hotbar
    jobs-per-page: 5

world:
  disable-portals: true
