package top.ourisland.creepersiarena.defaultcontent;

import org.junit.jupiter.api.Test;
import top.ourisland.creepersiarena.api.extension.ICiaExtension;

import java.nio.charset.StandardCharsets;
import java.util.Objects;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

class DefaultContentExtensionMetadataTest {

    @Test
    void generatedDescriptorAndServiceProviderPointToDefaultContentExtension() throws Exception {
        assertTrue(ICiaExtension.class.isAssignableFrom(DefaultContentExtension.class));

        String descriptor = resource("cia-extension.yml");
        String service = resource("META-INF/services/top.ourisland.creepersiarena.api.extension.ICiaExtension");

        assertTrue(descriptor.contains("id: \"cia-default-content\""));
        assertTrue(descriptor.contains("name: \"CreepersIArena Default Content\""));
        assertTrue(descriptor.contains("order: EARLY"));
        assertEquals("top.ourisland.creepersiarena.defaultcontent.DefaultContentExtension", service.strip());
    }

    private String resource(String path) throws Exception {
        try (
                var input = Objects.requireNonNull(
                        getClass().getClassLoader().getResourceAsStream(path),
                        path + " must be generated by @CiaExtensionInfo"
                )
        ) {
            return new String(input.readAllBytes(), StandardCharsets.UTF_8);
        }
    }

}
